_COMMON_HEAD = """\
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="preconnect" href="https://cdn.jsdelivr.net">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <style>
    :root { --bg:#f5f7fb; --surface:#fff; --surface-2:#f9fafb; --ink:#18202f; --muted:#667085; --line:#d9e0ea; --line-soft:#edf1f6; --brand:#0f766e; --brand-dark:#115e59; --accent:#2563eb; --warn:#b7791f; --danger:#b42318; --success:#067647; --shadow:0 14px 36px rgba(15,23,42,.08); }
    * { letter-spacing:0; }
    body { min-height:100vh; background:var(--bg); color:var(--ink); font-family:Inter,"Pretendard","Noto Sans KR",system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
    a { color:var(--brand-dark); text-decoration:none; } a:hover { color:var(--brand); }
    .app-nav { position:sticky; top:0; z-index:20; background:rgba(255,255,255,.95)!important; border-bottom:1px solid var(--line); backdrop-filter:blur(12px); }
    .brand-mark { width:34px; height:34px; border-radius:8px; display:inline-flex; align-items:center; justify-content:center; background:var(--ink); color:#fff; font-size:.86rem; font-weight:800; }
    .brand-title { font-weight:800; color:var(--ink); }
    .page-shell { max-width:1180px; margin:0 auto; padding:28px 20px 52px; } .page-shell-wide { max-width:1440px; margin:0 auto; padding:28px 24px 52px; }
    .eyebrow { color:var(--brand-dark); font-size:.76rem; font-weight:800; text-transform:uppercase; }
    .page-title { margin:4px 0 8px; font-size:clamp(1.65rem,2.8vw,2.45rem); font-weight:800; line-height:1.15; }
    .page-subtitle { max-width:760px; color:var(--muted); font-size:.98rem; line-height:1.65; }
    .section-card,.card { background:var(--surface); border:1px solid var(--line); border-radius:8px; box-shadow:var(--shadow); }
    .card-header { background:var(--surface); border-bottom:1px solid var(--line-soft); color:var(--ink); font-weight:800; padding:16px 18px; }
    .metric-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:12px; } .metric-grid.four { grid-template-columns:repeat(4,minmax(0,1fr)); }
    .metric-tile { min-height:108px; padding:18px; border:1px solid var(--line-soft); border-radius:8px; background:var(--surface-2); }
    .metric-label { color:var(--muted); font-size:.78rem; font-weight:700; text-transform:uppercase; } .stat-num { margin-top:6px; font-size:2rem; font-weight:850; line-height:1; color:var(--ink); } .metric-note { margin-top:8px; color:var(--muted); font-size:.82rem; }
    .status-strip { display:flex; gap:10px; flex-wrap:wrap; padding-top:14px; border-top:1px solid var(--line-soft); } .status-chip { display:inline-flex; align-items:center; gap:8px; padding:8px 10px; border-radius:8px; background:var(--surface-2); border:1px solid var(--line-soft); color:var(--muted); font-size:.84rem; font-weight:700; } .status-dot { width:8px; height:8px; border-radius:50%; background:var(--muted); } .status-dot.ready { background:var(--success); } .status-dot.missing { background:#cbd5e1; }
    .pipeline-grid { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:10px; } .pipeline-step { min-height:116px; padding:15px; text-align:left; border:1px solid var(--line); border-radius:8px; background:#fff; color:var(--ink); transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease; } .pipeline-step:hover { transform:translateY(-1px); border-color:var(--brand); box-shadow:0 10px 22px rgba(15,118,110,.12); } .pipeline-step:disabled { opacity:.52; transform:none; box-shadow:none; }
    .step-index { color:var(--brand-dark); font-size:.76rem; font-weight:800; } .step-title { display:block; margin-top:10px; font-weight:800; } .step-desc { display:block; margin-top:5px; color:var(--muted); font-size:.78rem; line-height:1.45; }
    .command-bar { display:flex; gap:10px; flex-wrap:wrap; align-items:center; padding-top:16px; border-top:1px solid var(--line-soft); }
    .btn { border-radius:8px; font-weight:800; min-height:40px; } .btn-primary,.btn-danger { background:var(--brand); border-color:var(--brand); color:#fff; } .btn-primary:hover,.btn-danger:hover { background:var(--brand-dark); border-color:var(--brand-dark); }
    .btn-outline-dark,.btn-outline-success,.btn-outline-primary,.btn-outline-warning,.btn-outline-secondary,.btn-outline-danger { color:var(--ink); border-color:var(--line); background:#fff; } .btn-outline-dark:hover,.btn-outline-success:hover,.btn-outline-primary:hover,.btn-outline-warning:hover,.btn-outline-secondary:hover,.btn-outline-danger:hover { color:#fff; border-color:var(--ink); background:var(--ink); }
    .badge { border-radius:999px; padding:.44rem .62rem; font-weight:800; } .bg-info{background:#dbeafe!important;color:#1d4ed8!important}.bg-warning{background:#fef3c7!important;color:#92400e!important}.bg-success{background:#dcfce7!important;color:#166534!important}.bg-danger{background:#fee2e2!important;color:#991b1b!important}.bg-secondary{background:#e2e8f0!important;color:#334155!important}.bg-dark{background:#18202f!important;color:#fff!important}
    .text-secondary{color:var(--muted)!important}.text-danger{color:var(--danger)!important}.text-success{color:var(--success)!important}.text-warning{color:var(--warn)!important}.text-info{color:var(--accent)!important}
    #log-area { background:#0f172a; color:#dbeafe; font-family:"Cascadia Mono","SFMono-Regular",Consolas,monospace; font-size:.82rem; height:430px; overflow-y:auto; padding:18px; white-space:pre-wrap; word-break:break-word; }
    .table { color:var(--ink); margin:0; } .table thead th { background:#f8fafc; color:#475467; font-size:.76rem; text-transform:uppercase; border-bottom:1px solid var(--line); white-space:nowrap; } .table tbody td { border-bottom:1px solid var(--line-soft); vertical-align:middle; } .vuln-row td{background:#fff7f7!important}.safe-row td{background:#fff!important}
    .empty-state { padding:36px; border:1px dashed var(--line); border-radius:8px; background:var(--surface); color:var(--muted); } code,.font-monospace{color:#344054}
    @media (max-width:900px){.pipeline-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.metric-grid,.metric-grid.four{grid-template-columns:repeat(2,minmax(0,1fr))}} @media (max-width:560px){.page-shell,.page-shell-wide{padding:20px 14px 40px}.pipeline-grid,.metric-grid,.metric-grid.four{grid-template-columns:1fr}.command-bar .btn,.command-bar a{width:100%}}
  </style>"""

_MAIN_HTML = """\
<!DOCTYPE html><html lang="en"><head><title>LADS Security Operations</title>""" + _COMMON_HEAD + """</head><body>
<nav class="navbar app-nav px-3 py-3"><div class="container-fluid"><a class="d-flex align-items-center gap-2" href="/"><span class="brand-mark">LD</span><span class="brand-title">LADS</span></a><div class="d-flex align-items-center gap-2 ms-auto"><a class="btn btn-outline-dark btn-sm" href="/runs">Runs</a><a class="btn btn-outline-dark btn-sm" href="/exec_results">Execution</a><a class="btn btn-primary btn-sm" href="/findings">Findings</a></div></div></nav>
<main class="page-shell"><section class="mb-4"><div class="eyebrow">Security Automation Console</div><h1 class="page-title">LLM-Assisted Web Vulnerability Operations</h1><p class="page-subtitle">Control crawling, payload generation, fuzzing, execution, and validation from one polished operations surface with immediate visibility into artifacts and risk metrics.</p></section>
<section class="section-card mb-4"><div class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2"><span>Assessment Status</span><span class="badge bg-secondary">Target {{ base_url }}</span></div><div class="card-body">{% if summary or exec_summary %}<div class="metric-grid">{% if summary %}<div class="metric-tile"><div class="metric-label">Scan Tests</div><div class="stat-num text-info">{{ summary.total }}</div><div class="metric-note">Completed scan checks</div></div><div class="metric-tile"><div class="metric-label">Findings</div><div class="stat-num text-danger">{{ summary.vulns }}</div><div class="metric-note">Potential vulnerable cases</div></div><div class="metric-tile"><div class="metric-label">Risk Rate</div><div class="stat-num text-warning">{{ "%.1f"|format(summary.rate) }}%</div><div class="metric-note">Ratio across all tests</div></div>{% endif %}{% if exec_summary %}<div class="metric-tile"><div class="metric-label">Executed</div><div class="stat-num">{{ exec_summary.total }}</div><div class="metric-note">OK {{ exec_summary.ok }} / Timeout {{ exec_summary.timeout }}</div></div>{% endif %}</div>{% else %}<div class="empty-state">No execution metrics yet. Start the pipeline to populate operational telemetry.</div>{% endif %}<div class="status-strip mt-3">{% for label, ok in file_status %}<span class="status-chip"><span class="status-dot {% if ok %}ready{% else %}missing{% endif %}"></span>{{ label }}</span>{% endfor %}</div></div></section>
<section class="section-card mb-4"><div class="card-header">Assessment Pipeline</div><div class="card-body"><div class="pipeline-grid"><button class="pipeline-step" onclick="runTask('crawl')"><span class="step-index">01</span><span class="step-title">Crawl & Map</span><span class="step-desc">Discover pages and candidate inputs.</span></button><button class="pipeline-step" onclick="runTask('payload')"><span class="step-index">02</span><span class="step-title">Generate Payloads</span><span class="step-desc">Create context-aware attack candidates.</span></button><button class="pipeline-step" onclick="runTask('fuzz')"><span class="step-index">03</span><span class="step-title">Plan Fuzzing</span><span class="step-desc">Build parameter-level execution tasks.</span></button><button class="pipeline-step" onclick="runTask('execute')"><span class="step-index">04</span><span class="step-title">Execute Fuzzing</span><span class="step-desc">Send requests and collect responses.</span></button><button class="pipeline-step" onclick="runTask('validate')"><span class="step-index">05</span><span class="step-title">Validate Findings</span><span class="step-desc">Promote evidence-backed results.</span></button></div><div class="command-bar mt-4"><button class="btn btn-primary" onclick="runTaskAll()">Run Full Pipeline</button><a class="btn btn-outline-dark" href="/results">Scan Results</a><a class="btn btn-outline-dark" href="/exec_results">Execution Results</a><a class="btn btn-outline-dark" href="/findings">Findings</a></div></div></section>
<section class="section-card mb-4" id="log-card" style="display:none"><div class="card-header d-flex justify-content-between align-items-center"><span id="log-title">Execution Log</span><span id="log-badge" class="badge bg-warning">Running</span></div><div id="log-area"></div></section></main>
<script>var _es=null;function runTask(task){_startStream('/stream/'+task)}function runTaskAll(){_startStream('/stream/all')}var _labels={crawl:'Crawl & Map',payload:'Generate Payloads',scan:'Run Scan',fuzz:'Plan Fuzzing',execute:'Execute Fuzzing',validate:'Validate Findings',all:'Full Pipeline'};function _setButtons(disabled){document.querySelectorAll('button').forEach(function(b){b.disabled=disabled})}function _startStream(url){if(_es){_es.close();_es=null}var logCard=document.getElementById('log-card'),logArea=document.getElementById('log-area'),logTitle=document.getElementById('log-title'),logBadge=document.getElementById('log-badge');var taskName=url.split('/stream/')[1].split('?')[0];logCard.style.display='block';logTitle.textContent=(_labels[taskName]||taskName)+' Log';logBadge.textContent='Running';logBadge.className='badge bg-warning';logArea.textContent='';_setButtons(true);logCard.scrollIntoView({behavior:'smooth',block:'start'});_es=new EventSource(url);_es.onmessage=function(e){if(e.data==='__DONE__'){_es.close();_es=null;logBadge.textContent='Completed';logBadge.className='badge bg-success';_setButtons(false);setTimeout(function(){location.reload()},1600);return}var line=document.createElement('div');if(e.data.indexOf('[ERROR]')!==-1)line.style.color='#fecaca';else if(e.data.indexOf('[WARN]')!==-1)line.style.color='#fde68a';line.textContent=e.data;logArea.appendChild(line);logArea.scrollTop=logArea.scrollHeight};_es.onerror=function(){if(_es){_es.close();_es=null}logBadge.textContent='Error';logBadge.className='badge bg-danger';_setButtons(false);var line=document.createElement('div');line.style.color='#fecaca';line.textContent='[Connection error - check server status]';logArea.appendChild(line)}};</script></body></html>"""

def _page_header(title, eyebrow, subtitle):
    return '<section class="mb-4"><div class="eyebrow">{}</div><h1 class="page-title">{}</h1><p class="page-subtitle">{}</p></section>'.format(eyebrow, title, subtitle)

_RESULTS_HTML = """\
<!DOCTYPE html><html lang="en"><head><title>LADS - Scan Results</title>""" + _COMMON_HEAD + """</head><body><nav class="navbar app-nav px-3 py-3"><div class="container-fluid"><a class="d-flex align-items-center gap-2" href="/"><span class="brand-mark">LD</span><span class="brand-title">LADS</span></a><span class="text-secondary ms-3 me-auto">Scan Results</span><a href="/" class="btn btn-outline-dark btn-sm">Dashboard</a></div></nav><main class="page-shell-wide">""" + _page_header("Scan Results", "Assessment Results", "Review response evidence and vulnerability decisions for every tested point.") + """{% if not results %}<div class="empty-state">No scan results are available. Run an assessment from the dashboard first.</div>{% else %}<section class="section-card mb-4"><div class="card-body"><div class="metric-grid"><div class="metric-tile"><div class="metric-label">Total Tests</div><div class="stat-num text-info">{{ total }}</div></div><div class="metric-tile"><div class="metric-label">Vulnerable</div><div class="stat-num text-danger">{{ n_vuln }}</div></div><div class="metric-tile"><div class="metric-label">Risk Rate</div><div class="stat-num text-warning">{{ "%.1f"|format(rate) }}%</div></div></div></div></section><section class="section-card"><div class="card-header">Detailed Results</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Point</th><th>Type</th><th>Payload</th><th>Status</th><th>Size</th><th>Latency</th><th>Decision</th></tr></thead><tbody>{% for r in results %}<tr class="{% if r.vulnerable %}vuln-row{% else %}safe-row{% endif %}"><td style="max-width:180px;" class="text-break">{{ r.point }}</td><td>{{ r.vuln_type }}</td><td style="max-width:320px;" class="text-break font-monospace">{{ r.payload }}</td><td>{% if r.response %}{{ r.response.status }}{% else %}-{% endif %}</td><td>{% if r.response %}{{ r.response.length }}{% else %}-{% endif %}</td><td>{% if r.response and r.response.elapsed is not none %}{{ "%.2f"|format(r.response.elapsed) }}s{% else %}-{% endif %}</td><td>{% if r.vulnerable %}<span class="badge bg-danger">Vulnerable</span>{% else %}<span class="badge bg-success">Clean</span>{% endif %}</td></tr>{% endfor %}</tbody></table></div></section>{% endif %}</main></body></html>"""

_EXEC_HTML = """\
<!DOCTYPE html><html lang="en"><head><title>LADS - Execution Results</title>""" + _COMMON_HEAD + """</head><body><nav class="navbar app-nav px-3 py-3"><div class="container-fluid"><a class="d-flex align-items-center gap-2" href="/"><span class="brand-mark">LD</span><span class="brand-title">LADS</span></a><span class="text-secondary ms-3 me-auto">Execution Results</span><a href="/" class="btn btn-outline-dark btn-sm">Dashboard</a></div></nav><main class="page-shell-wide">""" + _page_header("Fuzzing Execution Results", "Execution Telemetry", "Inspect request-level status, response time, and error details produced by the executor.") + """{% if not results %}<div class="empty-state">No execution results are available. Run fuzzing from the dashboard first.</div>{% else %}<section class="section-card mb-4"><div class="card-body"><div class="metric-grid four"><div class="metric-tile"><div class="metric-label">Total Requests</div><div class="stat-num text-info">{{ total }}</div></div><div class="metric-tile"><div class="metric-label">Success</div><div class="stat-num text-success">{{ ok }}</div></div><div class="metric-tile"><div class="metric-label">Timeout</div><div class="stat-num text-warning">{{ timeout }}</div></div><div class="metric-tile"><div class="metric-label">Errors</div><div class="stat-num text-danger">{{ err }}</div></div></div></div></section><section class="section-card"><div class="card-header">Execution Detail</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>task_id</th><th>Parameter</th><th>Scope</th><th>Mode</th><th>Location</th><th>Type</th><th>Payload</th><th>Status</th><th>Length</th><th>Time</th><th>Error</th></tr></thead><tbody>{% for r in results %}<tr class="{% if r.error %}vuln-row{% endif %}"><td class="font-monospace text-secondary">{{ r.task_id }}</td><td class="font-monospace">{{ r.inject_param }}</td><td><span class="badge {% if r.inject_scope == 'multiple' %}bg-warning{% else %}bg-secondary{% endif %}">{{ r.inject_scope }}</span></td><td><span class="badge {% if r.inject_mode == 'append' %}bg-info{% else %}bg-secondary{% endif %}">{{ r.inject_mode }}</span></td><td>{{ r.inject_location }}</td><td>{{ r.vuln_type }}</td><td style="max-width:260px;" class="text-break font-monospace">{{ r.payload }}</td><td>{{ r.status_code or '-' }}</td><td>{{ r.response_length or '-' }}</td><td>{% if r.response_time %}{{ "%.3f"|format(r.response_time) }}s{% else %}-{% endif %}</td><td class="text-danger">{{ r.error or '' }}</td></tr>{% endfor %}</tbody></table></div></section>{% endif %}</main></body></html>"""

_FINDINGS_HTML = """\
<!DOCTYPE html><html lang="en"><head><title>LADS - Findings</title>""" + _COMMON_HEAD + """</head><body><nav class="navbar app-nav px-3 py-3"><div class="container-fluid"><a class="d-flex align-items-center gap-2" href="/"><span class="brand-mark">LD</span><span class="brand-title">LADS</span></a><span class="text-secondary ms-3 me-auto">Findings</span><a href="/" class="btn btn-outline-dark btn-sm">Dashboard</a></div></nav><main class="page-shell-wide">""" + _page_header("Validated Findings", "Evidence-backed Results", "Confirmed findings promoted by the validation stage.") + """{% if not findings %}<div class="empty-state">No findings are available. Run validation from the dashboard first.</div>{% else %}<section class="section-card mb-4"><div class="card-body"><div class="metric-grid"><div class="metric-tile"><div class="metric-label">Findings</div><div class="stat-num text-danger">{{ findings|length }}</div></div><div class="metric-tile"><div class="metric-label">XSS</div><div class="stat-num text-warning">{{ xss_cnt }}</div></div><div class="metric-tile"><div class="metric-label">SQLi</div><div class="stat-num text-danger">{{ sqli_cnt }}</div></div></div></div></section><section class="section-card"><div class="card-header">Detected Vulnerabilities</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Type</th><th>Target</th><th>Parameter</th><th>Payload</th><th>Status</th><th>Latency</th><th>Evidence</th></tr></thead><tbody>{% for f in findings %}<tr class="vuln-row"><td><span class="badge bg-danger">{{ f.vuln_type or '-' }}</span></td><td class="text-muted" style="max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">{{ f.url or f.point }}</td><td><code>{{ f.param }}</code></td><td style="max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" class="font-monospace">{{ f.payload }}</td><td>{{ f.status }}</td><td>{{ f.elapsed }}s</td><td class="text-danger fw-semibold">{{ f.evidence }}</td></tr>{% endfor %}</tbody></table></div></section>{% endif %}</main></body></html>"""
